### ISSUE TITLE
On Android in Release builds - Calling Posthog().setContext causes Posthog to no longer log any events

### ISSUE THREAD

**Issue by ghost** [PostHog/posthog-flutter#18]
pubspec:
```
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  posthog_flutter: ^2.0.3
```

```
Flutter 2.2.1 • channel stable • https://github.com/flutter/flutter.git  
Framework • revision 02c026b03c (8 weeks ago) • 2021-05-27 12:24:44 -0700
Engine • revision 0fdb562ac8
Tools • Dart 2.13.1
```

Tested on Samsung A20e and A40

### To Reproduce

- Run the [example ](https://github.com/PostHog/posthog-flutter/blob/master/example/lib/main.dart)in release mode on Android - because `setContext` is called in `main` no further actions are ever logged to posthog.
- Remove `setContext` [call from main](https://github.com/PostHog/posthog-flutter/blob/31e69a0246a48fd5264df75c95b7e8dfd162597b/example/lib/main.dart#L24), run the demo and the `ButtonClicked` event is captured successfuly. 
- Tap `Update Context` button
- No further events are logged to posthog
